# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo-maps-pods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for demo-maps-pods

    pod 'GoogleMaps'
    pod 'GooglePlaces'

end
